# Generated by Django 4.2.29 on 2026-03-27 15:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('card', '0002_alter_card_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ext_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('sender_card_expiry', models.CharField(help_text='Format: MM/YY', max_length=5)),
                ('sender_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('receiver_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('sending_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(choices=[('643', 'RUB'), ('840', 'USD')], default='840', max_length=3)),
                ('receiving_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=15)),
                ('state', models.CharField(choices=[('created', 'Created'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='created', max_length=10)),
                ('try_count', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(3)])),
                ('otp', models.CharField(blank=True, max_length=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('receiver_card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_transfers', to='card.card')),
                ('sender_card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_transfers', to='card.card')),
            ],
        ),
    ]
