# Generated by Django 4.2.29 on 2026-03-27 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(help_text='Xatolik kodi', unique=True)),
                ('en', models.CharField(max_length=255, verbose_name='English')),
                ('ru', models.CharField(max_length=255, verbose_name='Russian')),
                ('uz', models.CharField(max_length=255, verbose_name='Uzbek')),
            ],
            options={
                'verbose_name': 'Error Message',
                'verbose_name_plural': 'Error Messages',
            },
        ),
    ]
