# Generated by Django 6.0.3 on 2026-03-11 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('in_active', 'In Active'), ('expired', 'Expired')], max_length=30)),
                ('expired', models.DateField()),
            ],
        ),
    ]
